baseURL: https://masputrawae.github.io/
languageCode: id
title: My Notes
timeZone: Asia/Jakarta
enableEmoji: true
enableGitInfo: true

services:
  googleAnalytics:
    id: G-W9TMTZZYG5
privacy:
  googleAnalytics:
    disable: false
    respectDoNotTrack: true

#===================
# TAXONOMIES
#===================
taxonomies:
  tag: tags
  category: categories
  stage: stage
  source: source

#===================
# CASCADE
#===================
cascade:
  - _target:
      path: '{/quickly/**,/cheat_sheet/**,/copas/**,/references/**}'
    repoBasePath: notes

#===================
# CUSTOM OUTPUT
#===================
mediaType: 'application/json'
outputFormats:
  search:
    mediaType: 'application/json'
    baseName: 'search'
    isPlainText: true
    notAlternative: true

  manifest:
    mediaType            : 'application/json'
    baseName             : 'manifest'
    isPlainText          : true
    notAlternative       : true
  
  random-page:
    mediaType            : 'text/html'
    baseName             : 'random-page'
    isPlainText          : true
    notAlternative       : true

outputs:
  home:
    - html
    - rss
    - sitemap
    - random-page
    - search
    - manifest

module:
  hugoVersion:
    extended: true
    min: 0.149.0

  mounts:
    - source: node_modules/bootstrap-icons/icons
      target: assets/icons

    - source: images
      target: assets/images

    - source: assets
      target: assets

    - source: images
      target: static/images
    
    - source: favicons
      target: static/favicons

    - source: static
      target: static
